/**
 * deploy.ts
 *
 * Deploys the DealRegistry TealScript contract to AlgoKit LocalNet.
 *
 * Usage:
 *   npm run deploy
 *
 * The script will print the App ID to stdout.
 * Copy that value into frontend/.env.local:
 *   NEXT_PUBLIC_DEAL_REGISTRY_APP_ID=<printed value>
 */

import { AlgorandClient } from "@algorandfoundation/algokit-utils";
import { DealRegistryClient } from "../artifacts/DealRegistry/DealRegistryClient.js";
import * as algosdk from "algosdk";

// ─── LocalNet connection ───────────────────────────────────────────────────────

/**
 * AlgorandClient configured for AlgoKit LocalNet defaults:
 *   algod  : http://localhost:4001  token: aaaa…
 *   kmd    : http://localhost:4002  token: aaaa…
 *   indexer: http://localhost:8980  token: aaaa…
 */
const algorand = AlgorandClient.fromConfig({
  algodConfig: {
    server: "http://localhost",
    port: 4001,
    token: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  },
  kmdConfig: {
    server: "http://localhost",
    port: 4002,
    token: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  },
});

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log("═══════════════════════════════════════════════");
  console.log("  OTC Trustless Swap — DealRegistry Deployment");
  console.log("═══════════════════════════════════════════════");

  // ── 1. Resolve the deployer account from KMD ──────────────────────────────
  //
  // AlgoKit LocalNet ships with a pre-funded "default" KMD wallet.
  // `getOrCreateKmdWalletAccount` returns the first available account.

  const kmdClient = algorand.kmd;
  const wallets = await kmdClient.listWallets();

  const defaultWallet = wallets.wallets.find(
    (w: { name: string }) => w.name === "unencrypted-default-wallet"
  );

  if (!defaultWallet) {
    throw new Error(
      "KMD default wallet not found. Is AlgoKit LocalNet running? (`algokit localnet start`)"
    );
  }

  const walletHandle = (
    await kmdClient.initWalletHandle(defaultWallet.id, "")
  ).wallet_handle_token;

  const { addresses } = await kmdClient.listKeysInWallet(walletHandle);

  if (!addresses || addresses.length === 0) {
    throw new Error("No accounts found in KMD default wallet.");
  }

  const deployerAddress = addresses[0];
  console.log(`\n✔ Deployer: ${deployerAddress}`);

  // Wrap the KMD signer so AlgorandClient can use it transparently.
  const signerAccount = algorand.account.kmd(walletHandle, deployerAddress);

  // ── 2. Build the typed application client ─────────────────────────────────
  //
  // DealRegistryClient is generated by `npm run build` (tealscript compiler).
  // It provides fully-typed methods matching every ABI method in the contract.

  const client = new DealRegistryClient(
    {
      sender: { addr: deployerAddress, signer: signerAccount.signer },
      resolveBy: "id",
      id: 0, // 0 = deploy a new instance
    },
    algorand.client.algod
  );

  // ── 3. Deploy (create) the contract ───────────────────────────────────────

  console.log("\n⏳ Deploying DealRegistry…");

  const { appId, appAddress, transaction, confirmation } =
    await client.create.createApplication({});

  console.log("\n✔ Deployment successful!");
  console.log(`   App ID      : ${appId}`);
  console.log(`   App Address : ${appAddress}`);
  console.log(`   Txn ID      : ${transaction.txID()}`);
  console.log(`   Round       : ${confirmation?.confirmedRound}`);

  // ── 4. Fund the app account (minimum balance requirement) ─────────────────
  //
  // Every Algorand account (including app accounts) requires a 0.1 ALGO MBR
  // to exist on-chain. We fund it with a small buffer.

  const MBR_BUFFER_MICROALGOS = 200_000; // 0.2 ALGO

  await algorand.send.payment({
    sender: deployerAddress,
    signer: signerAccount.signer,
    receiver: appAddress,
    amount: algosdk.microalgos(MBR_BUFFER_MICROALGOS),
    note: new Uint8Array(Buffer.from("DealRegistry MBR funding")),
  });

  console.log(`\n✔ Funded app account with ${MBR_BUFFER_MICROALGOS / 1e6} ALGO`);

  // ── 5. Print .env instructions ────────────────────────────────────────────

  console.log("\n═══════════════════════════════════════════════");
  console.log("  Copy this line into frontend/.env.local:");
  console.log(`  NEXT_PUBLIC_DEAL_REGISTRY_APP_ID=${appId}`);
  console.log("═══════════════════════════════════════════════\n");
}

main().catch((err) => {
  console.error("\n✖ Deployment failed:", err);
  process.exit(1);
});
